---
title: "DEA 1 - Budweiser"
author: "Shijo Joseph & Douglas Yip"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Budweiser
## Executive Summary
### The purpose of this review is to provide you white space options based on the category insights to 558 Breweries across the US.  
###Our insights that we are sharing are based on the ABV and IBU content by State.
###Our review recommends that the following  opportuntities that your company should consider
###   1) XXX
###   2) YYY

```{r load packages}
#load different libraries and function to enable us to complete this analysis
library(readr)
library(tidyr) #enables piping
library(dplyr)#enables enhancement to cleanse data
library(ggplot2)
library(caret) #enaables classfication and regression training
library(e1071)

#how do i not print the code #echo off

```

```{r load data sets}
#uploads the data into R to start analysis
#shijo can you take the link of where we pull the CSV directly from Github?

Breweries <- read_csv("https://raw.githubusercontent.com/sajoseph-smu/Case-Study-1---Budwieser/main/Breweries.csv", show_col_types = FALSE) 

summary(Breweries)
Beers <- read_csv("https://raw.githubusercontent.com/sajoseph-smu/Case-Study-1---Budwieser/main/Beers.csv", show_col_types = FALSE)
summary(Beers)

```




```{r 1. How many breweries are present in each state}
#This code will identify the number of breweries for each state
#How many Breweries are in each state?

SummaryBrewery <- Breweries %>% count(State, sort = TRUE)
names(SummaryBrewery)[2] <- "Brewery_Count"
#Summary of Breweries 
SummaryBrewery

# Top 25 States with Most Breweries
SummaryBrewery %>% head(25) %>% ggplot(mapping = aes(x = reorder(State,-Brewery_Count), y = Brewery_Count, fill = State)) + geom_bar(stat = 'identity') + ggtitle("Top 25 States by Brewery Count") + xlab("States") + ylab("Brewery Count") +geom_text(aes(label = format(Brewery_Count,big.mark =',')), position = position_dodge(width = .9), vjust = -.25)

# Bottom 25 States with Most Breweries
SummaryBrewery %>% tail(25) %>% ggplot(mapping = aes(x = reorder(State,Brewery_Count), y = Brewery_Count, fill = State)) + geom_bar(stat = 'identity') + ggtitle("Bottom 25 States by Brewery Count") + xlab("States") + ylab("Brewery Count") +geom_text(aes(label = format(Brewery_Count,big.mark =',')), position = position_dodge(width = .9), vjust = -.25)

```


```{r 2&3. Data Merge and clean}
#This code will merge the Data with assigning each beer with the brewery and location

#Merge Data
#outer join (keep all observations from both dataframes)
names(Beers)[5] <- "Brew_ID"
names(Breweries)[2] <- "Brewery_Name"
bbdf <- merge(Beers,Breweries, by = "Brew_ID")

#Cleanse data
#need to figure out how to fill in the IBU, I thnk we can use Style and ABV to formulate the IBU for those empty spots

<<<<<<< HEAD
#clean age
ABV.median <- median(bbdf$ABV, na.rm = TRUE)
bbdf[is.na(bbdf$ABV),"ABV"] <- ABV.median

=======
bbdf_clean = na.omit(bbdf)
>>>>>>> ac908a909afb10373ed9c733c8fa394ba62350a3
```

```{r 4. Median of alcohol content and bitterness by each state.}
#This code will create a table of Medians for ABV and IBU for each state and graphically display a bar chart (how would a bar chart do that? wouldn't a box plot be better? Question to ask)
#Table and bar chart of alcohol

# created a clean table with stats for ABV and IBU
bbdf_clean_stats = bbdf_clean %>% group_by(State) %>% summarise(Mean_ABV=mean(ABV), Max_ABV=max(ABV), Min_ABV=min(ABV), Median_ABV=median(ABV), Std_ABV=sd(ABV),Mean_IBU=mean(IBU), Max_IBU=max(IBU), Min_IBU=min(IBU), Median_IBU=median(IBU), Std_IBU=sd(IBU))

# Clean table with Medians for ABV and IBU
bbdf_clean_Medians = bbdf_clean_stats %>% select(State, Median_ABV, Median_IBU)
bbdf_clean_Medians


# Top 25 States by Median ABV
bbdf_clean_Medians %>% head(25) %>% ggplot(mapping = aes(x = reorder(State,Median_ABV), y = Median_ABV, fill = State)) + geom_bar(stat = 'identity') + ggtitle("Top 25 States by Median ABV") + xlab("States") + ylab("ABV") +ylim(0,.08) +geom_text(aes(label = format(Median_ABV,big.mark =',')), position = position_dodge(width = .6), hjust = -.25) + coord_flip()

# Bottom 25 States by Median ABV
bbdf_clean_Medians %>% tail(25) %>% ggplot(mapping = aes(x = reorder(State,-Median_ABV), y = Median_ABV, fill = State)) + geom_bar(stat = 'identity') + ggtitle("Bottom 25 States by Median ABV") + xlab("States") + ylab("ABV") +ylim(0,.08) +geom_text(aes(label = format(Median_ABV,big.mark =',')), position = position_dodge(width = .6), hjust = -.25) + coord_flip()


# Top 25 States by Median IBU
bbdf_clean_Medians %>% head(25) %>% ggplot(mapping = aes(x = reorder(State,Median_IBU), y = Median_IBU, fill = State)) + geom_bar(stat = 'identity') + ggtitle("Top 25 States by Median IBU") + xlab("States") + ylab("IBU") +ylim(0,70) +geom_text(aes(label = format(Median_IBU,big.mark =',')), position = position_dodge(width = .6), hjust = -.25) + coord_flip()

# Bottom 25 States by Median IBU
bbdf_clean_Medians %>% tail(25) %>% ggplot(mapping = aes(x = reorder(State,-Median_IBU), y = Median_IBU, fill = State)) + geom_bar(stat = 'identity') + ggtitle("Bottom 25 States by Median IBU") + xlab("States") + ylab("IBU") +ylim(0,70) +geom_text(aes(label = format(Median_IBU,big.mark =',')), position = position_dodge(width = .6), hjust = -.25) + coord_flip()



```

```{r 5. Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?}
#This code will identify which State has the highest ABV and IBU beers.


# State with the max ABV
bbdf_clean_stats %>% filter(Max_ABV == max(Max_ABV))

#State with the max IBU
bbdf_clean_stats %>% filter(Max_IBU == max(Max_IBU))

```

```{r 6.Comment on the summary statistics and distribution of the ABV variable.}
#This code will create a summary statistic of the ABV variable

# already have that in the bbdf_clean_stats 

# created a clean table with stats for ABV 
bbdf_clean_stats = bbdf_clean %>% group_by(State) %>% summarise(Mean_ABV=mean(ABV), Max_ABV=max(ABV), Min_ABV=min(ABV), Median_ABV=median(ABV), Std_ABV=sd(ABV))


```


```{r 7. Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.  Make your best judgment of a relationship and EXPLAIN your answer}
# Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.  Make your best judgment of a relationship and EXPLAIN your answer

bbdf_clean %>% ggplot(mapping = aes(x = ABV, y = IBU)) + geom_point(mapping = aes(x = ABV, y = IBU, color = State), position = "jitter") +  geom_smooth(method='lm', formula= y~x) + ggtitle("ABV vs IBU") + xlab("ABV") + ylab("IBU") 

# there is a linear positive correlation between ABV and IBU based on the linear model of the data set.



```

```{r 8..  Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA).  You decide to use KNN classification to investigate this relationship.  Provide statistical evidence one way or the other. You can of course assume your audience is comfortable with percentages … KNN is very easy to understand conceptually. }



# building the Ales and IP data frame and creating a flag for OtherAles and IPA 

bbdf_Ales = bbdf_clean %>% filter(str_detect(Style,"(IPA| Ale)"))

bbdf_Ales = bbdf_Ales %>% mutate(IPAFlag = case_when(str_detect(bbdf_Ales$Style,"IPA") == TRUE ~ "IPA", TRUE ~ "Other Ales" ))

bbdf_Ales$IPAFlag = as.factor(bbdf_Ales$IPAFlag)

library(class)
library(caret)
library(e1071)

# find the best K 
set.seed(1)
iterations = 500
numks = 90
splitPerc = .70

masterAcc = matrix(nrow = iterations, ncol = numks)

for(j in 1:iterations)
{
  trainIndices = sample(1:dim(bbdf_Ales)[1],round(splitPerc * dim(bbdf_Ales)[1]))
  train = bbdf_Ales[trainIndices,]
  test = bbdf_Ales[-trainIndices,]
  for(i in 1:numks)
  {
    classifications = knn(train[,c(4,5)],test[,c(4,5)],train$IPAFlag, prob = TRUE, k = i)
    CM = confusionMatrix(table(classifications,test$IPAFlag))
    masterAcc[j,i] = CM$overall[1]
  }
  
}

MeanAcc = colMeans(masterAcc)


# find out the best K and accuracy  and plot it
which.max(MeanAcc)
max(MeanAcc)
plot(seq(1,numks,1),MeanAcc, type = "l")
abline(v = 5, col = 'green')
abline(h = .8589, col = 'green')

     
# run the knn with the best K

    classifications = knn(train[,c(4,5)],test[,c(4,5)],train$IPAFlag, prob = TRUE, k = 5)
    CM = confusionMatrix(table(classifications,test$IPAFlag))
    CM
  

# Douglas.. can you write up the conclusion here :) 



```


```{r 9..  Knock their socks off!  Find one other useful inference from the data that you feel Budweiser may be able to find value in.  You must convince them why it is important and back up your conviction with appropriate statistical evidence.  }


# 



# there is a linear positive correlation between ABV and IBU based on the linear model of the data set.



```