---
title: "DEA 1 - Budweiser"
author: "Shijo Joseph & Douglas Yip"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Budweiser
## Executive Summary
### The purpose of this review is to provide you white space options based on the category insights to 558 Breweries across the US.  
###Our insights that we are sharing are based on the ABV and IBU content by State.
###Our review recommends that the following  opportuntities that your company should consider
###   1) XXX
###   2) YYY

```{r load packages}
#load different libraries and function to enable us to complete this analysis
library(readr)
library(tidyr) #enables piping
library(dplyr)#enables enhancement to cleanse data
library(ggplot2)
library(caret) #enaables classfication and regression training
library(e1071)

#how do i not print the code #echo off

```

```{r load data sets}
#uploads the data into R to start analysis
#shijo can you take the link of where we pull the CSV directly from Github?

Breweries <- read_csv("https://raw.githubusercontent.com/sajoseph-smu/Case-Study-1---Budwieser/main/Breweries.csv", show_col_types = FALSE) 

summary(Breweries)
Beers <- read_csv("https://raw.githubusercontent.com/sajoseph-smu/Case-Study-1---Budwieser/main/Beers.csv", show_col_types = FALSE)
summary(Beers)

```




```{r 1. How many breweries are present in each state}
#This code will identify the number of breweries for each state
#How many Breweries are in each state?

SummaryBrewery <- Breweries %>% count(State, sort = TRUE)
names(SummaryBrewery)[2] <- "Brewery Count"
#Summary of Breweries 
SummaryBrewery

```


```{r 2&3. Data Merge and clean}
#This code will merge the Data with assigning each beer with the brewery and location

#Merge Data
#outer join (keep all observations from both dataframes)
names(Beers)[5] <- "Brew_ID"
names(Breweries)[2] <- "Brewery Name"
bbdf <- merge(Beers,Breweries, by = "Brew_ID")

#Cleanse data
#need to figure out how to fill in the IBU, I thnk we can use Style and ABV to formulate the IBU for those empty spots


```

```{r 4. Median of alcohol content and bitterness by each state.}
#This code will create a table of Medians for ABV and IBU for each state and graphically display a bar chart (how would a bar chart do that? wouldn't a box plot be better? Question to ask)
#Table and bar chart of alcohol



```

```{r 5. Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?}
#This code will identify which State has the highest ABV and IBU beers.



```

```{r 6.Comment on the summary statistics and distribution of the ABV variable.}
#This code will create a summary statistic of the ABV variable


```


```{r 7. Shijo magic}


```
